SCOPE infrastructural PROTO = GMQ;

PUBLISHABLE publishable_sample {
	STRUCT NONEXTENDABLE ScreenPoint screenPoint;
};

MESSAGE infrastructural:ScreenPoint=1 = STRUCT ScreenPoint;

STRUCT NONEXTENDABLE ScreenPoint {
  INTEGER x;
  INTEGER y;
};
